general_config:
  openai_config:
    model_name: gpt-3.5-turbo-1106
    cutting_edge_model: gpt-4-1106-preview
    assistant_id: 
    file_id: 
    thread_id: 
    knowledge_file: 
    description: 
    instructions: |